name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
        - name: Lighthouse CI Action
        - uses: treosh/lighthouse-ci-action@v3
